jobs:
  darkube_build_mind-trail-client_mindtrail_hamravesh-c13:
    container:
      image: hamravesh/darkube-cli:v1.1
      options: --user root
    env:
      IMAGE_NAME: registry.hamdocker.ir/mindtrail/mind-trail-client
    runs-on: ubuntu-latest
    steps:
      - name: checkout commit
        uses: actions/checkout@v4
      - name: darkube-cli build & push
        run: 'darkube build --push -t $IMAGE_NAME:${GITHUB_SHA:0:7} -t $IMAGE_NAME:${GITHUB_REF_NAME}
        --docker-auth-config ${{secrets.DOCKER_AUTH_CONFIG}} --workdir . --file ./Dockerfile
        --builg-arg NEXT_PUBLIC_URL=${{vars.NEXT_PUBLIC_URL}}
        --build-context . '
  darkube_deploy_mind-trail-client_mindtrail_hamravesh-c13:
    container: hamravesh/darkube-cli:v1.1
    needs: darkube_build_mind-trail-client_mindtrail_hamravesh-c13
    runs-on: ubuntu-latest
    steps:
      - name: darkube-cli deploy
        run: darkube deploy --token ${{secrets.DEPLOY_TOKEN_MIND_TRAIL_CLIENT_MINDTRAIL_HAMRAVESH_C13}}
          --app-id ${{secrets.APP_ID_MIND_TRAIL_CLIENT_MINDTRAIL_HAMRAVESH_C13}} --image-tag
          ${GITHUB_SHA:0:7} --job-id ${GITHUB_RUN_ID}
'on':
  push:
    branches:
      - main